// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPc3AZOSK6oc99yfqI6FOd1SpwIEvaQcM',
    appId: '1:932785227398:web:ad03faaba58b6343047307',
    messagingSenderId: '932785227398',
    projectId: 'eos-4sis-3c03a',
    authDomain: 'eos-4sis-3c03a.firebaseapp.com',
    storageBucket: 'eos-4sis-3c03a.appspot.com',
    measurementId: 'G-721Y168QWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFjTZZO3af3v2mXm95gw-U_TusO0bjLI',
    appId: '1:932785227398:android:b672ab6cd5223471047307',
    messagingSenderId: '932785227398',
    projectId: 'eos-4sis-3c03a',
    storageBucket: 'eos-4sis-3c03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvhtsdZFPQrBnFqoZnbC89nbuMIFYYus',
    appId: '1:932785227398:ios:0bb3bae11e1378ea047307',
    messagingSenderId: '932785227398',
    projectId: 'eos-4sis-3c03a',
    storageBucket: 'eos-4sis-3c03a.appspot.com',
    iosBundleId: 'com.eos.fsis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvhtsdZFPQrBnFqoZnbC89nbuMIFYYus',
    appId: '1:932785227398:ios:f8962e7f070e6b8d047307',
    messagingSenderId: '932785227398',
    projectId: 'eos-4sis-3c03a',
    storageBucket: 'eos-4sis-3c03a.appspot.com',
    iosBundleId: 'com.eos.fsis.RunnerTests',
  );
}
